[project]
name = "ape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.9.3",
    "pydantic>=2.6.0", 
    "loguru>=0.7.2",
    "httpx",
    "ollama>=0.1.6",
    "python-dotenv>=1.0.0",
]